### ISSUE TITLE
MindbodyAPI Error: InvalidCredentials - Permission denied.

### ISSUE THREAD

**Issue by ghodkekrishna** [wmds/MindBodyAPIBundle#1]
actually i want to use Mindbodyapi in my symfony2 project but it will giving me error of MindbodyAPI Error: InvalidCredentials - Permission denied. 
![issue](https://f.cloud.github.com/assets/4829791/973753/defc1d8a-063c-11e3-9822-b2ef5fb9a09b.png)

**Comment by wmds** [comment]
You are trying to use the API with demo website, please check because as far as remember you need different credentials for the sandbox site.

Also, double check the credentials are correct.
